name: Template Latest Youtube
on:
  schedule:
    # Runs at 08h00 on Sunday
    - cron: '0 8 * * 0'
  workflow_dispatch:
jobs:
  update-readme-with-youtube-activity:
    name: Update this repo's README with latest activity from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          commit_message: "Updated readme with the latest youtube data"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPmM6RAkfC0CY2gGudIhWQA"
          custom_tags: "videoId/yt:videoid/,publishDate/published/"
          max_post_count: 6
          template: "<a href="$url"><img src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg" />$newline $title</a>$newline"